apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  template:
    metadata:
      labels: 
        app: webapp
    spec:
      containers:
      - name: webapp
        image: r3ap3rpy/python-webapp:v1
        ports:
        - containerPort: 8080
